import type { Metadata } from "next";

import "./globals.css";
import TransitionProvider from "@/components/templates/TransitionProvider";
import CustomCursor from "@/components/atoms/CustomCursor";
import Navigation from "@/components/organisms/Navigation";
import Footer from "@/components/organisms/Footer";



import localFont from 'next/font/local'

const cocogoose = localFont({
  src: './fonts/Cocogoose.otf',
  variable: '--font-cocogoose',
})

const helveticaCondensed = localFont({
  src: [
    {
      path: './fonts/HelveticaNeueCondensedBold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/HelveticaNeueCondensedBlack.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica-condensed',
})



export const metadata: Metadata = {
  title: "LeWrap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cocogoose.variable} ${helveticaCondensed.variable} antialiased overflow-x-hidden`}
      >
        <CustomCursor />
        <Navigation />
        <TransitionProvider>
          {children}
          <Footer />
        </TransitionProvider>
      </body>
    </html>
  );
}
